// AUTO-GENERATED by scripts/gen-site-image-slots.mjs — do not edit by hand.
// Each slot's `fallback` is the image originally shipped in the component.
// Admins override any slot from /admin/imaj; overrides live in
// public.site_images and win over these defaults.

export type SiteImageSlot = {
  key: string;
  section: string;
  label: string;
  fallback: string;
};

export const SITE_IMAGE_SLOTS: readonly SiteImageSlot[] = [
  { key: 'hero-1', section: 'Ewo (an wo paj la)', label: 'Ewo (an wo paj la) — imaj 1', fallback: 'https://images.pexels.com/photos/163186/globuli-medical-bless-you-homeopathy-163186.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop' },
  { key: 'hero-2', section: 'Ewo (an wo paj la)', label: 'Ewo (an wo paj la) — imaj 2', fallback: 'https://images.pexels.com/photos/105028/pexels-photo-105028.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop' },
  { key: 'hero-3', section: 'Ewo (an wo paj la)', label: 'Ewo (an wo paj la) — imaj 3', fallback: 'https://images.pexels.com/photos/7523449/pexels-photo-7523449.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop' },
  { key: 'hero-4', section: 'Ewo (an wo paj la)', label: 'Ewo (an wo paj la) — imaj 4', fallback: 'https://images.pexels.com/photos/8391429/pexels-photo-8391429.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop' },
  { key: 'hero-5', section: 'Ewo (an wo paj la)', label: 'Ewo (an wo paj la) — imaj 5', fallback: 'https://images.pexels.com/photos/7615621/pexels-photo-7615621.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop' },
  { key: 'hero-6', section: 'Ewo (an wo paj la)', label: 'Ewo (an wo paj la) — imaj 6', fallback: 'https://images.pexels.com/photos/6850901/pexels-photo-6850901.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop' },
  { key: 'hero-7', section: 'Ewo (an wo paj la)', label: 'Ewo (an wo paj la) — imaj 7', fallback: 'https://images.pexels.com/photos/5480091/pexels-photo-5480091.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop' },
  { key: 'hero-8', section: 'Ewo (an wo paj la)', label: 'Ewo (an wo paj la) — imaj 8', fallback: 'https://images.pexels.com/photos/5480036/pexels-photo-5480036.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop' },
  { key: 'hero-9', section: 'Ewo (an wo paj la)', label: 'Ewo (an wo paj la) — imaj 9', fallback: 'https://images.pexels.com/photos/7526026/pexels-photo-7526026.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop' },
  { key: 'hero-10', section: 'Ewo (an wo paj la)', label: 'Ewo (an wo paj la) — imaj 10', fallback: 'https://images.pexels.com/photos/7526062/pexels-photo-7526062.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop' },
  { key: 'hero-11', section: 'Ewo (an wo paj la)', label: 'Ewo (an wo paj la) — imaj 11', fallback: 'https://images.pexels.com/photos/6076150/pexels-photo-6076150.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop' },
  { key: 'hero-12', section: 'Ewo (an wo paj la)', label: 'Ewo (an wo paj la) — imaj 12', fallback: 'https://images.pexels.com/photos/7615466/pexels-photo-7615466.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop' },
  { key: 'carousel-1', section: 'Karousèl', label: 'Karousèl — imaj 1', fallback: 'https://images.unsplash.com/photo-1473773508845-188df298d2d1?q=80&w=1200' },
  { key: 'carousel-2', section: 'Karousèl', label: 'Karousèl — imaj 2', fallback: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?q=80&w=1200' },
  { key: 'carousel-3', section: 'Karousèl', label: 'Karousèl — imaj 3', fallback: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?q=80&w=1200' },
  { key: 'carousel-4', section: 'Karousèl', label: 'Karousèl — imaj 4', fallback: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?q=80&w=1200' },
  { key: 'carousel-5', section: 'Karousèl', label: 'Karousèl — imaj 5', fallback: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?q=80&w=1200' },
  { key: 'carousel-6', section: 'Karousèl', label: 'Karousèl — imaj 6', fallback: 'https://images.unsplash.com/photo-1507692049790-de58290a4334?q=80&w=1200' },
  { key: 'carousel-7', section: 'Karousèl', label: 'Karousèl — imaj 7', fallback: 'https://images.unsplash.com/photo-1529390079861-591de354faf5?q=80&w=1200' },
  { key: 'carousel-8', section: 'Karousèl', label: 'Karousèl — imaj 8', fallback: 'https://images.unsplash.com/photo-1611078489935-0cb964de46d6?q=80&w=1200' },
  { key: 'testimonial-1', section: 'Temwayaj', label: 'Temwayaj — imaj 1', fallback: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80' },
  { key: 'testimonial-2', section: 'Temwayaj', label: 'Temwayaj — imaj 2', fallback: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80' },
  { key: 'testimonial-3', section: 'Temwayaj', label: 'Temwayaj — imaj 3', fallback: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80' },
  { key: 'about-1', section: 'Apwopo nou', label: 'Apwopo nou — imaj 1', fallback: 'https://images.unsplash.com/photo-1611078489935-0cb964de46d6?auto=format&fit=crop&w=900&q=80' },
  { key: 'about-2', section: 'Apwopo nou', label: 'Apwopo nou — imaj 2', fallback: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&w=600&q=80' },
];
