-- Generated by scripts/import-doz.mjs — "Dòz ak Fòmil" articles from
-- medikaplant.org imported as native doz_recipes rows. Re-runnable
-- (upsert on slug), so re-importing refreshes the bodies.

insert into public.doz_recipes
  (slug, title, tag, excerpt, body_html, category_id, published, published_at)
values
  ('beny-pou-pye-cho', 'Beny pou Pye Cho', 'Sikilasyon', '🌿 Beny pou Pye: Sipò pou sikilasyon, cho-frèt, kout pye, “batri” Si pye w konn ap fè cho-frèt, 👉 youn cho pandan lòt la frèt, 👉 oswa tou de pye yo toujou ap cho. Beny sa a fèt…', '<h2>🌿 <strong>Beny pou Pye: Sipò pou sikilasyon, cho-frèt, kout pye, “batri”</strong></h2>
<p>Si pye w konn ap fè cho-frèt,<br>👉 youn cho pandan lòt la frèt,<br>👉 oswa tou de pye yo toujou ap cho.</p>
<p><strong>Beny sa a fèt pou ede balanse tanperati pye yo epi soutni sikilasyon.</strong></p>
<p>📌 Menm si se yon sèl pye ki gen pwoblèm nan, <strong>toujou tranpe tou de pye yo ansanm</strong>.<br></p>
<h3><strong>ENGREDYAN:</strong></h3>
<ul>
<li>3 gwo men fèy gwayav</li>
</ul>
<ul>
<li><strong>PREPARASYON:</strong></li>

<li>Bouyi fèy yo pandan anviwon <strong>10 minit</strong></li>

<li>Vide dlo a nan yon veso ki apwopriye</li>

<li>Pandan li toujou cho:
<ul>
<li>Lage <strong>1 gwo bout glas</strong> ladan</li>

<li>Ajoute <strong>3 chòt klè blan fò</strong></li>

<li>Ajoute <strong>3 priz bikabonat (baking soda)</strong></li>
</ul>
<h3><br><strong>DIPLIS:</strong></h3>
<ul>
<li>Si w gen <strong>pye anfle (edèm / retansyon dlo)</strong>:<br>👉 Ou ka ajoute <strong>sèl lanmè</strong> ak kèk <strong>fèy mant</strong><br>👉 Pa neglije <strong>diminye sèl</strong> nan manje w</li>

<li>Gen plis dòz pou pye anfle sou sit la:<br>🌐 https://medikaplant.org/doz-natirel-pou-pye-k-kenbe-dlo</li>

<li>Si se <strong>atwoz oswa atrit</strong>:<br>🌐 https://medikaplant.org/beny-fey-kont-atwoz</li>
</ul>
<p><br><br>🌿 <strong>Medikaplant</strong><br>🌐 www.medikaplant.org</p>
<p>🌿 Beny pou Pye Cho: Sipò pou sikilasyon, cho-frèt, kout pye, “batri”</p>
<p>Tretman pou Maladi Fredite nan Medsin Tradisyonèl</p>
<p>🌺 SORÈL | FLÈ IBISIK | FLè Jamayik</p>
<p>🌿 Klin-tòks | Clean-Tox | Key Detox Herbs</p>
<p>🌿✨ Folat: Seròm Biyo Ki Ka Ede Timoun Yo Devlope Pi Byen✨🌿</p>
<p>🌿 DÒZ POU KOUPE DYARE KI PA VLE KANPE SOU TIMOUN</p>
<p>🔍 Hizòp Vs, Bazilik: Diferans Kle</p>
<p>🌿 RASIN VETIVÈ: YON TREZÒ MEDISINAL NOU NEGLIJE</p>
<p>Detòks: Pwotokòl Antiparazit &amp; Lyennaj (Binder)</p>
<p>Kèk bagay ou dwe fè anvan ou kòmanse nenpòt gerizon natirèl</p></li></ul>', (select id from public.doz_categories where slug = 'doz-ak-fomil'), true, now()),
  ('tretman-maladi-fredite', 'Tretman pou Maladi Fredite nan Medsin Tradisyonèl', 'Fredite', 'Tretman pou Maladi Fredite nan Medsin Tradisyonèl Chinwa Nan Medsin Tradisyonèl Chinwa , yo rekonèt yon kategori maladi yo rele Fredite (Cold diseases). Menm jan sa ye nan kilti…', '<p><strong>Tretman pou Maladi Fredite nan Medsin Tradisyonèl Chinwa</strong></p>
<p>Nan <strong>Medsin Tradisyonèl Chinwa</strong>, yo rekonèt yon kategori maladi yo rele <strong>Fredite</strong> (Cold diseases). Menm jan sa ye nan kilti pa nou, fredi sa a ka chita nan lestomak oswa nan san an. Maladi sa yo gen 3 gwo siy ki mache avèk yo:</p>
<p>1. Moun nan pa vle wè fredi ditou (sa rann doulè a pi rèd).</p>
<p>2. Moun nan <strong>pa gen lafyèv</strong>.</p>
<p>3. Moun nan pa santi swaf dlo.</p>
<p><strong>1. Remèd Pou Lestomak k ap Boule (Asidite)</strong></p>
<p>Si w ap soufri ak lestomak k ap boule oswa doulè apre ou fin manje, men yon resèt ki baze sou koki fwi lanmè:</p>
<p>• <strong>Lekòl Medsin:</strong> Sèvi ak koki zwit griye.</p>
<p>• <strong>Preparasyon:</strong> Griye koki yo byen griye epi kraze yo jiskaske yo tounen yon <strong>poud ki byen fen</strong>.</p>
<p>• <strong>Dozaj:</strong> Pran <strong>2 gram</strong> poud sa a nan yon vè dlo tyèd, 3 fwa pa jou (2 oswa 3 èdtan apre ou fin manje).</p>
<p><strong>2. Te Pou Chase Fredite (Lestomak anfle, Dyare, ak Tous)</strong></p>
<p>Resèt sa a te bay gwo rezilta nan Medsin Tradisyonèl Chinwa pou 34 kalite ka kote fredi antre nan kò a, tankou: lestomak k ap rale, vant k ap bouyi, dyare, doulè nan pwatrin, tous, ak doulè règ lakay medam yo.</p>
<p>• <strong>Konpozisyon:</strong></p>
<p>• 10 a 15 gram <strong>Reglis (Licorice)</strong>.</p>
<p>• 10 a 15 gram <strong>Jenjanm (sèk)</strong>.</p>
<p>• <strong>Preparasyon:</strong> Melanje de plant sa yo pou fè yon sèl dòz pou jounen an. Bouyi yo nan dlo pou fè yon te cho.</p>
<p>• <strong>Pouvwa:</strong> Chalè Jenjanm nan ak dousè <strong>Reglis (Licorice)</strong> la konbat fredi ki nan san an ak nan zantray yo.</p>
<p><strong>3. Remèd Pwav Nwa pou Gwo Doulè Lestomak</strong></p>
<p>Pou ka kote «&nbsp;fredi&nbsp;» a tèlman fò li bay gwo kranp nan lestomak, yon doktè Chinwa te rapòte siksè ak melanj sa a:</p>
<p>• <strong>Sa w ap bezwen:</strong></p>
<p>• 10 grenn <strong>Pwav nwa</strong> (grenn yo dwe kri).</p>
<p>• 3 grenn <strong>Piman wouj</strong>.</p>
<p>• <strong>Remak:</strong> Epis sa yo gen yon «&nbsp;enèji cho&nbsp;» ki debloke sikilasyon an nan lestomak la.</p>
<p><strong>🩺 Fredite Medsin Endijèn Ayisyen</strong></p>
<p>Nan peyi nou Ayiti, nou gen menm konpreyansyon sa a sou <strong>Maladi Fredite</strong>. Lè yon moun «&nbsp;gen fredi&nbsp;», nou konnen se yon kondisyon kote kò a pèdi balans chalè li, souvan apre yon akouchman, yon kout lè, oswa dlo frèt ki antre sou yon kò cho.</p>
<p><strong>Sou Medikaplant n ap gen pou nou fè yon pòs espesyal talè konsa sou ka fredite nan Medsin Endijèn Ayisyen an.</strong><br></p>
<p>N ap gen pou prezante nou yon seri <strong>Plant Cho</strong> ki nan jaden nou, ki gen pouvwa pou chanje tanperati kò a epi chase fredi, tankou:</p>
<p>• <strong>Jenjanm Anmè</strong></p>
<p>• <strong>Flè ak fèy Pwa Kongo</strong></p>
<p>• <strong>Boujon ak tèt bwa tabak</strong></p>
<p>• …ak kèk lòt plant cho patikilyè.</p>
<p>Resete branche pou dekouvri kijan zansèt nou yo te konn sèvi ak chalè lanati pou geri kò a!</p>
<p>🌿 Beny pou Pye Cho: Sipò pou sikilasyon, cho-frèt, kout pye, “batri”</p>
<p>Tretman pou Maladi Fredite nan Medsin Tradisyonèl</p>
<p>🌺 SORÈL | FLÈ IBISIK | FLè Jamayik</p>
<p>🌿 Klin-tòks | Clean-Tox | Key Detox Herbs</p>
<p>🌿✨ Folat: Seròm Biyo Ki Ka Ede Timoun Yo Devlope Pi Byen✨🌿</p>
<p>🌿 DÒZ POU KOUPE DYARE KI PA VLE KANPE SOU TIMOUN</p>
<p>🔍 Hizòp Vs, Bazilik: Diferans Kle</p>
<p>🌿 RASIN VETIVÈ: YON TREZÒ MEDISINAL NOU NEGLIJE</p>
<p>Detòks: Pwotokòl Antiparazit &amp; Lyennaj (Binder)</p>
<p>Kèk bagay ou dwe fè anvan ou kòmanse nenpòt gerizon natirèl</p>', (select id from public.doz_categories where slug = 'doz-ak-fomil'), true, now()),
  ('folat-serom-biyo-timoun', 'Folat: Seròm Biyo pou timoun devlope pi byen', 'Nitrisyon', '#Medikaplant #ByennètNatirèl #PlantPaPlant #NitrisyonPouTimoun Folate: The Green Vitamin of Life 🌿✨ Folat: Rale Siwo Lavi nan Plant Yo ✨🌿 🇭🇹 Kisa Folate ye? Folat (oswa…', '<p><strong>#Medikaplant #ByennètNatirèl #PlantPaPlant #NitrisyonPouTimoun</strong></p>
<h3><br><em><strong>Folate: The Green Vitamin of Life</strong> </em><br>🌿✨ Folat: Rale Siwo Lavi nan Plant Yo  ✨🌿<br><br>🇭🇹 <strong>Kisa Folate ye?</strong></h3>
<p><strong>Folat (oswa Vitamin B9)</strong> se yon eleman esansyèl kò a bezwen pou fè san, pwodui nouvo selil, epi kenbe sistèm nève a an bon sante.<br>Plant se pi bon sous natirèl li! Fòm sentetik li rele <strong>asid folik</strong>, yo konn mete l nan pen, sereyal, ak pasta endistriyèl — men folate ki soti nan plant pi fasil pou kò a absòbe.</p>
<h2><br>🌿 <strong>Pi Bon Sous Folat nan Plant </strong></h2>
<h3>🥬 <strong>Legim Vèt Fonse yo </strong></h3>
<ul>
<li><strong>Zepina (Spinach)</strong></li>

<li><strong>Chou frize (Kale)</strong></li>

<li><strong>Fèy navèt, romèn, ak kolad (Collard greens)</strong><br><br>➡️ Yo chaje klowofil (chlorophyll), fè (iron), ak Vitamin B  — sa se fondasyon pou renouvèlman selil yo ka fèt.</li>
</ul>
<h3>🥦 <strong>Legim Krisifè (Cruciferous Vegetables</strong>)</h3>
<ul>
<li><strong>Brokoli, Aspèj, Chou Brisèl (Brussels Sprouts)</strong><br>➡️ Excellent for detoxification and gut support.</li>
</ul>
<h3>🥕 <strong>Lòt Legim | Other Veggies</strong></h3>
<ul>
<li><strong>Bètrav, Choufleur, pwa vèt (Peas)</strong><br>➡️ Boost circulation and support healthy blood production.</li>
</ul>
<h3><br>🫘 <strong>Grenn ak Legim </strong>| Fèy (Sispann di salad fèy se raje, koumanse manje yo plis)</h3>
<h3>🍊 <strong>Fwi Fòtifye Ki Plen ak Folat</strong></h3>
<ul>
<li><strong>Lantiy (Lentils)</strong></li>

<li><strong>Pwa kongo, pwa chich, pwa rouj (Kidney beans)</strong></li>

<li><strong>Pistach (Peanuts)</strong><br>➡️ Plen pwoteyin + folat = Founisè enèji natirèl.<br></li>
</ul>
<ul>
<li><strong>Zoranj, Papay, Bannann, Melon (Cantaloup)</strong><br>➡️ Refreshing and supportive of immune function.</li>
</ul>
<h3>🥑 <strong>Lòt Sous Natirèl | Other Natural Sources</strong></h3>
<ul>
<li><strong>Zaboka (Avocado)</strong></li>

<li><strong>Nwa (walnuts)</strong></li>

<li><strong>Grenn Sola (Sunflower seeds)</strong><br>➡️ Give creamy texture, healthy fats, and folate synergy.</li>
</ul>
<h2><br>🧃 <strong>Jis ak Dòz Melanj Natirèl Pou Timoun</strong></h2>
<h3>🥬💚 <strong>1️⃣ Ji Enèji Vèt Green </strong></h3>
<p><strong>Engredyan | Ingredients:</strong></p>
<ul>
<li>1 gwo men zepina (spinach)</li>

<li>½ zaboka (ripe avocado)</li>

<li>1 zoranj (peze)</li>

<li>½ sitwon (lime)</li>

<li>1 ti mango oswa bannann pou dousè</li>
</ul>
<p><strong>Benefis:</strong> Chaje ak anpil folat, Vitamin C ak fè ki kore vitalite ak gangans chak jou. <br>👧🏽 Sa kòrèk anpil pou timoun anvan yo ale lekòl nan maten — Li fè yo rete fokis ak kenbe enèji yo djanm djanm pandan jounen an.<br><br></p>
<h3>🥕🍋 <strong>2️⃣ Bètrav &amp; Ji Si (sitwon, zonraj, ets) Ki Ba w Bèl Ekla</strong></h3>
<p><strong>Engredyan | Ingredients:</strong></p>
<ul>
<li>1 ti bètrav (kwit oswa tou kri)</li>

<li>1 zoranj</li>

<li>1 ti bout jenjanm (ginger)</li>

<li>1 ti ven/sik kann natirèl oswa siwomyèl </li>
</ul>
<p><strong>Benefis:</strong> Amelyore san ak sikilasyon, ranfòse sistèm imin timoun yo.<br><br></p>
<h3>🍌🥭 <strong>3️⃣ Ji Blennde (Smoothie) Pou Ti Timoun Ki Pa Renmen Legim</strong></h3>
<p><strong>Engredyan:</strong></p>
<ul>
<li>1 fig bannann</li>

<li>1 mango oswa moso papay</li>

<li>1 men zepina (rache mete nan ji blennde a)</li>

<li>½ tas lèt amand/zanmann oswa gen moun ki itilize lèt avwàn (si w pa gen amand lan, men si w ka evite avwàn nan sa pi bon toujou)</li>
</ul>
<p><strong>Benefis:</strong> Fè timoun yo jwenn folat ak fib san yo pa menm rann yo kont se legim y ap manje!<br><br></p>
<h3>🍛🥗 <strong>4️⃣ Melanj Manje Pou Timoun </strong>| Byen Konbine</h3>
<ul>
<li><strong>Pwa chich + Bwokoli + Diri entegre</strong> → Enèji &amp; Kwasans selil</li>

<li><strong>Lantiy bouyi + Bannann vèt ak legim vèt</strong> → Folat + balans fè (iron)</li>

<li><strong>Zaboka + zoranj ak grenn flè solèy (sunflower seeds)</strong> → Bon gra  &amp; Sipò pou Sèvo</li>
</ul>
<h3><br>🌿✨ <strong>Konsèy Medikaplant</strong></h3>
<p>Manje oswa bay timoun yo manje vejetal/fèy/legim/fwi  koulè vèt yo chak jou — yo chaje vitamin K: se vitamin K nan fòm natirèl ki nouri chak selil.<br>Fè timoun yo jwenn folat la sou fòm fasil y ap renmen: ji, smouti, oswa ti manje byen balanse.<br><br>💚 <strong>Manje vivan → Sante vivan.</strong> Timoun Nòmal, panse, aji ak pale byen.<br><br><br><strong>Medikaplant</strong></p>
<p><strong>#Medikaplant #PlantPaPlant #Folate #VitaminB9 #Zepina #Zaboka #Bètrav #Papay #Sorel #SanteTimoun #ByennètNatirèl #NitrisyonHolistik</strong></p>
<p>🌿 Beny pou Pye Cho: Sipò pou sikilasyon, cho-frèt, kout pye, “batri”</p>
<p>Tretman pou Maladi Fredite nan Medsin Tradisyonèl</p>
<p>🌺 SORÈL | FLÈ IBISIK | FLè Jamayik</p>
<p>🌿 Klin-tòks | Clean-Tox | Key Detox Herbs</p>
<p>🌿✨ Folat: Seròm Biyo Ki Ka Ede Timoun Yo Devlope Pi Byen✨🌿</p>
<p>🌿 DÒZ POU KOUPE DYARE KI PA VLE KANPE SOU TIMOUN</p>
<p>🔍 Hizòp Vs, Bazilik: Diferans Kle</p>
<p>🌿 RASIN VETIVÈ: YON TREZÒ MEDISINAL NOU NEGLIJE</p>
<p>Detòks: Pwotokòl Antiparazit &amp; Lyennaj (Binder)</p>
<p>Kèk bagay ou dwe fè anvan ou kòmanse nenpòt gerizon natirèl</p>', (select id from public.doz_categories where slug = 'doz-ak-fomil'), true, now()),
  ('rasin-vetive', 'Rasin Vetivè: yon trezò medisinal nou neglije', 'Dijesyon', '👉 VANT FÈ MAL | ILSÈ 👈 ENGREDYAN : Rasin ak Fèy Vetivè (Vetiveria zizanioides | Chrysopogon zizanioides) • Anglè: vetiver, khus (pa konfonn ak khus khus ki se yon lòt plant) •…', '<p>👉 VANT FÈ MAL | ILSÈ 👈</p>
<p><strong>ENGREDYAN</strong>: Rasin ak Fèy Vetivè<br>(Vetiveria zizanioides | Chrysopogon zizanioides)<br>• Anglè: vetiver, khus (pa konfonn ak khus khus ki se yon lòt plant)<br>• Fransè: vétiver, vétyver</p>
<p><strong>PREPARASYON | POZOLOJI<br></strong>• Pou ilsè ak vant fè mal: Pran 3 branch fèy vetivè.<br>• Si yo sèch: pile yo, sèvi ak 1 ti kiyè poud fèy la.<br>• Si yo frèch: mete 3 branch dirèk nan yon veso ak 2–3 tas dlo.<br>• Bouyi pandan 12 minit, pase nan paswa oswa grèp te.<br>• Bwè 2–3 fwa pa jou, pandan 3 jou.</p>
<p><strong>POUKISA VETIVÈ ENPÒTAN?</strong></p>
<p>Vetivè se yon plant mirak ki grandi natirèlman nan peyi cho tankou Ayiti.<br>• Rasin li yo long, santi bon, epi rezistan anpil. Yo ka antre fon nan tè a rive jiska 3 mèt, sa ki fè plant lan itil pou kontwole ewozyon epi pou kenbe tè fètil.<br>• Lwil esansyèl vetivè se youn nan pi chè lwil ki genyen sou planèt la: pri li konpare ak gazolin ak menm ak lò. Chak ane, mond lan pwodui anviwon 250 tòn lwil vetivè, epi yo itilize l nan 90% pafen oksidantal yo.<br>• Nan medsin tradisyonèl, vetivè toujou gen yon plas espesyal kòm yon plant ki detoksifye, kalme, ak geri.<br><br></p>
<p><br><strong>KÈK LÒT BENEFIS RASIN VETIVÈ GENYEN<br></strong>• Gaz, vè, parazit nan vant: fè dekoksyon ak rasin lan.<br>• Tèt fè mal san rete: bouyi branch ak rasin ansanm.<br>• Tonik jeneral: rasin lan ranfòse kò a, ogmante vitalite.<br>• Enfeksyon irinè: bouyi de twa bout rasin rasin yo.<br>• Pwoblèm fwa: seche rasin yo nan lonbraj (pa mete yo nan solèy), pile yo, mete nan dlo oswa melanje ak lòt plant.<br>• Lafyèv ak swe twòp: fè yon enfizyon ak rasin yo nan dlo cho.<br>• Tous ak grip: fè dekoksyon ak tout pati plant lan.<br>• Doulè rimatis &amp; nan zo: lwil vetivè a ou ka pase sou po a pou kalme doulè.<br>• Swen po &amp; pafen: lwil esansyèl la pwoteje po kont sechrès, bay yon bon odè pwofon ak natirèl.</p>
<p><br><br><br><strong>ISTWA KILTIRÈL AK ITILIZASYON VETIVÈ ANN AYITI</strong></p>
<p>Vetivè se pa sèlman yon plant medsin, men li fè pati lavi chak jou pèp ayisyen depi lontan:<br>• Nan medsin tradisyonèl: Rasin yo sèvi pou “netwaye san”, trete maladi fwa, ak chase vè nan vant.<br>• Nan atizana: Fèy ak rasin sèch yo itilize pou fè dra, tapi, panyen, menm kouvèti kay nan zòn riral.<br>• Nan rityèl espirityèl: Dlo vetivè konn sèvi kòm beny pou netwayaj espirityèl, kont move enèji, epi pou pote trankilite.<br>• Nan agrikilti: Yo plante vetivè bò ravin ak mòn pou kontwole ewozyon, paske rasin li mare tè a byen fò.<br>• Nan ekonomi lokal: Ayiti se youn nan pi gwo pwodiktè lwil vetivè nan mond lan; anpil fanmi nan sid Ayiti viv gras ak kiltivasyon ak transfòmasyon plant sa a.</p>
<p>Vetivè se vrèman yon plant ki ini sante, kilti, ak ekonomi ansanm.</p>
<p>⚠️ <em><strong>AVÈTISMAN</strong></em>:<br>Pa itilize pou fanm ansent, manman k ap bay tete, ni pou timoun ki poko gen 5 lane.</p>
<p>🌱 <strong>Medikaplant</strong><br>👉 www.medikaplant.org</p>
<p>📢 PATAJE PÒS SA a pou n kontinye kanpay fèy la avanse!</p>
<p>🌿 Beny pou Pye Cho: Sipò pou sikilasyon, cho-frèt, kout pye, “batri”</p>
<p>Tretman pou Maladi Fredite nan Medsin Tradisyonèl</p>
<p>🌺 SORÈL | FLÈ IBISIK | FLè Jamayik</p>
<p>🌿 Klin-tòks | Clean-Tox | Key Detox Herbs</p>
<p>🌿✨ Folat: Seròm Biyo Ki Ka Ede Timoun Yo Devlope Pi Byen✨🌿</p>
<p>🌿 DÒZ POU KOUPE DYARE KI PA VLE KANPE SOU TIMOUN</p>
<p>🔍 Hizòp Vs, Bazilik: Diferans Kle</p>
<p>🌿 RASIN VETIVÈ: YON TREZÒ MEDISINAL NOU NEGLIJE</p>
<p>Detòks: Pwotokòl Antiparazit &amp; Lyennaj (Binder)</p>
<p>Kèk bagay ou dwe fè anvan ou kòmanse nenpòt gerizon natirèl</p>', (select id from public.doz_categories where slug = 'doz-ak-fomil'), true, now()),
  ('spem-feb-tizan-labouyi', 'Spèm Fèb: Tizàn ak Labouyi', 'Fètilite', 'Medam ki bezwen ansent yo: menm si nou trete fibwòm ak kis la, pwoblèm twonp anfle a ak andometriyoz plis lòt bagay ki anpeche w ansent. Sonje sa ki enpòtan, anpil fwa se nèg la…', '<p>Medam ki bezwen ansent yo: menm si nou trete fibwòm ak kis la, pwoblèm twonp anfle a ak andometriyoz plis lòt bagay ki anpeche w ansent. Sonje sa ki enpòtan, anpil fwa se nèg la ki gen pwoblèm, pa ekzanp kantite ak kalite spèm nan fèb. Depi se konsa li p ap fasil pou n ansent si nèg la pa gen spèm bon kalite.</p>
<p>Pandan tretman nou an men se pou fè tretman pou mari nou oswa nèg nou pou amelyore ak ogmante kantite ak kalite spèm li pou l ka ansent nou pi fasil.</p>
<p><strong>Dòz #1</strong></p>
<p>1) Pou rafrechi yon ponyen fèy bazilit nan dlo tchèd chak maten</p>
<p><strong>Dòz #2</strong></p>
<p>2) LABOUYI = Pòmdetè + manyòk + kawòt + espageti; bouyi, blennde oubyen pile mete lèt pou mari w bwè sa pou prepare moman li pral antre nan fè bagay avèk ou<br></p>
<p><strong>Dòz #3</strong></p>
<p>Medikaplant gen pwòp fòmil pa n nou devlope pou ede rezoud pwoblèm spèm fèb ki pi grav yo. Se toujou ak plant nou konpoze yo, li senp epi l biyo. Konsa tou, li toujou bon pou moun nan ta detoksike tout sistèm kò l nèt pou amelyore sante jeneral li. </p>
<p> Pou labouyi a l ap bwè l chak de (2) fwa pa semèn<br></p>
<p>ENPÒTAN: Obsève ki koulè spèm mari nou. Koulè a ka ede n detèmine sante osw akalite spèm yo. Nou ka toujou di pèsonèl swen sante nou an sa pou l oryante n nan bon direksyon an.</p>
<p><strong>Medikaplant</strong></p>
<p>#Medikaplant | #Spèm_Fèb | #Bazilik | #Labouyi | #Remèd_Fèy</p>
<p>🌿 Beny pou Pye Cho: Sipò pou sikilasyon, cho-frèt, kout pye, “batri”</p>
<p>Tretman pou Maladi Fredite nan Medsin Tradisyonèl</p>
<p>🌺 SORÈL | FLÈ IBISIK | FLè Jamayik</p>
<p>🌿 Klin-tòks | Clean-Tox | Key Detox Herbs</p>
<p>🌿✨ Folat: Seròm Biyo Ki Ka Ede Timoun Yo Devlope Pi Byen✨🌿</p>
<p>🌿 DÒZ POU KOUPE DYARE KI PA VLE KANPE SOU TIMOUN</p>
<p>🔍 Hizòp Vs, Bazilik: Diferans Kle</p>
<p>🌿 RASIN VETIVÈ: YON TREZÒ MEDISINAL NOU NEGLIJE</p>
<p>Detòks: Pwotokòl Antiparazit &amp; Lyennaj (Binder)</p>
<p>Kèk bagay ou dwe fè anvan ou kòmanse nenpòt gerizon natirèl</p>', (select id from public.doz_categories where slug = 'doz-ak-fomil'), true, now()),
  ('doz-let-lokyostaz', 'Dòz pou Fanm ki gen Pwoblèm Lèt ak Lokyostaz', 'Apre akouchman', '→ Lokyotaz (Lochi): se pèt, ekoulman oswa senyen Apre-Akouchman. Dòz Plant pou Pòspatòm &amp; Pwodiksyon Lèt Lochi ak Lokyostaz Apre akouchman, tout fanm pase pa yon fenomèn…', '<p><em>→ Lokyotaz (Lochi): se pèt, ekoulman oswa senyen Apre-Akouchman.</em><br></p>
<p><strong>Dòz Plant pou Pòspatòm &amp; Pwodiksyon Lèt</strong><br></p>
<p><strong>Lochi ak Lokyostaz</strong><br>Apre akouchman, tout fanm pase pa yon fenomèn natirèl yo rele <strong>Lochi (Lochia)</strong>, ki se senyen ak dechay matris la jete pou netwaye apre tibebe fèt. Lochi a konn gen 3 faz:</p>
<ol>
<li><strong>Lochia Rubra / Cruenta</strong> – senyen wouj fonse, rive premye jou yo.</li>

<li><strong>Lochia Serosa</strong> – vin pi klè, yon melanj san ak likid.</li>

<li><strong>Lochia Alba / Purulenta</strong> – dènye etap la, pi blan oswa jòn klè.</li>
</ol>
<p>Pafwa lochi a konn <strong>rete bloke</strong> anndan matris la, sa rele <strong>Lokyostaz oswa Lokyokesis (Lochiostasis / Lochioschesis)</strong>. Lè sa rive, li ka lakòz doulè, enfeksyon, ak pwoblèm gerizon. Nan medsin tradisyonèl, plant itilize kòm yon mwayen natirèl pou ede <strong>netwaye matris la, ankouraje senyen koule nèt, epi evite blokaj</strong>.<br></p>
<p><strong>Pwoblèm Pwodiksyon Lèt</strong><br>Yon lòt difikilte fanm konn rankontre se <strong>pwodiksyon lèt pou bay tibebe</strong>. Genyen ki fè tout sa yo konnen, men lèt la pa desann ase. Sa konn gen rapò ak estrès, alimantasyon, oswa balans òmòn. Nan tradisyon medsin plant, gen fòmil ki rele <strong>galaktogòg</strong> (plant ki ankouraje laktasyon) pou ede ranfòse sekresyon lèt.</p>
<h2>Solisyon: <strong>Dòz ak Fòmil Ou ka fè ak 3 engredyan senp + 2 Lòt ou ka konsome</strong></h2>
<p><strong>Kèk Lòt Plant Ki Ka Ede w &amp; Benefis yo Genyen</strong></p>
<ul>
<li><strong>Fenouy (Foeniculum vulgare)</strong> – galaktogòg natirèl, ankouraje lèt desann, ede kont gaz ak kolik nan tibebe.</li>

<li><strong>Fenugreek (Trigonella foenum-graecum)</strong> – pi popilè pou ogmante lèt, amelyore dijesyon, ranfòse enèji manman.</li>

<li><strong>Basilik (Ocimum basilicum)</strong> – kalme sistèm nève a, ede ak balans òmòn.</li>

<li><strong>Anis (Pimpinella anisum)</strong> – ede lèt koule, diminye vant gonfle ak espas.</li>

<li><strong>Ortij / Nettle (Urtica dioica)</strong> – fèy rich an fè ak vitamin, ranfòse manman ki pèdi anpil san nan akouchman.</li>

<li><strong>Moringa / Doliv (Moringa oleifera)</strong> – tradisyonèlman itilize kòm «&nbsp;miracle tree&nbsp;», yon gwo sipò pou ogmante lèt, pote anpil vitamin A, C, fè ak kalsyòm.</li>

<li><strong>Zèb Sen Jan (St. John’s Wort – Hypericum perforatum)</strong> – tradisyonèlman itilize pou balans emosyonèl apre akouchman.<br></li>

<li><strong>Melanj Pwopriyetè Medikaplant</strong> – nou gen kèk pwodui ki fèt ak kèk plant tou ki ede netwaye matris la, ranfòse sistèm iminitè, epi soutni rekiperasyon jeneral fanm nan. Vizite Medikaplantshop.com pou w ka chwazi sa ou bezwen nan ka pa w la<br></li>
</ul>
<p><br>✨ <strong>Benefis Dòz la</strong></p>
<ul>
<li>Ede <strong>netwaye matris la</strong> pou evite lochi bloke (Lokyostaz).</li>

<li>Soutni <strong>gerizon natirèl</strong> apre akouchman.</li>

<li>Ogmante <strong>pwodiksyon lèt</strong> pou nouri tibebe yo.</li>

<li>Bay manman an <strong>fòs, mineral, ak vitamin</strong> pou reprann vitalite pi vit.</li>

<li>Sèvi kòm yon <strong>sipò iminitè</strong> pou evite enfeksyon.<br></li>
</ul>
<p><br><br>👩🏽‍🍼 <strong>Medikaplant se avni ak tradisyon ansanm</strong> – nou rasanble konesans fanm chay yo, ansyen medsin plant, ansanm ak syans modèn pou pote solisyon natirèl ki mache.</p>
<p><br><strong>Medikaplant</strong><br><br><br></p>
<p>______________</p>
<p>#Medikaplant | #fanm_chay | #postpartum| #akouchman | #lokyostaz |#lochio | #manke_lèt | #alètman | #FanmNouris |#ayiti | #kreyòl | #tradisyon |<br><em>⚠️ FDA pa t evalye deklarasyon sa yo. Pòs sa a pa fèt pou dyagnostike, trete, geri, oswa anpeche okenn maladi.</em></p>
<p>🌿 Beny pou Pye Cho: Sipò pou sikilasyon, cho-frèt, kout pye, “batri”</p>
<p>Tretman pou Maladi Fredite nan Medsin Tradisyonèl</p>
<p>🌺 SORÈL | FLÈ IBISIK | FLè Jamayik</p>
<p>🌿 Klin-tòks | Clean-Tox | Key Detox Herbs</p>
<p>🌿✨ Folat: Seròm Biyo Ki Ka Ede Timoun Yo Devlope Pi Byen✨🌿</p>
<p>🌿 DÒZ POU KOUPE DYARE KI PA VLE KANPE SOU TIMOUN</p>
<p>🔍 Hizòp Vs, Bazilik: Diferans Kle</p>
<p>🌿 RASIN VETIVÈ: YON TREZÒ MEDISINAL NOU NEGLIJE</p>
<p>Detòks: Pwotokòl Antiparazit &amp; Lyennaj (Binder)</p>
<p>Kèk bagay ou dwe fè anvan ou kòmanse nenpòt gerizon natirèl</p>', (select id from public.doz_categories where slug = 'doz-ak-fomil'), true, now()),
  ('horsetail-ke-chwal', 'Horsetail (Ke Chwal): Pwoblèm Ren ak Vesi', 'Ren ak vesi', 'Fikse Pwoblèm Ren, Vesi + Lòt Byenfè Medisinal Plant sa yo konn « Pwèl » la, non sa yo pran l soti nan non fransè a ki se « Prêle », li pa gen anyen pou wè ak plim moun, jan anpil…', '<p><em><strong>Fikse Pwoblèm Ren, Vesi + Lòt Byenfè Medisinal</strong></em></p>
<p>Plant sa yo konn «&nbsp;Pwèl&nbsp;» la, non sa yo pran l soti nan non fransè a ki se «&nbsp;Prêle&nbsp;», li pa gen anyen pou wè ak plim moun, jan anpil moun panse a.</p>
<p>Non anglè a ki pi popilè se «&nbsp;Horsetail&nbsp;», se konsa tou panyòl yo, bay plant sa menm non an men nan lang pa yo: Cola de Caballo. Se pou sa nou rele l an Kreyòl «&nbsp;Ke Chwal&nbsp;», non sa fè l jistis epi l byen tonbe tou. Men sa pa anpehe nou toujou ka rele l Pwèl.</p>
<p>Non syantifik:<em> Equisetum arvense</em></p>
<p>Fanmi: <em>Equisetaceae</em></p>
<p>Gen plizyè espès, nou dwe fè atansyon ak kiyès n ap itilize kòm remèd natirèl. Li pa difisil pou jwenn li achte, nou pa jwenn li an Ayiti fasil ni li pa popilè nan medsin tradisyonèl nou an, tandiske Sen Domeng machann fèy yo souvan genyen l. Nan kominote latino yo USA w ap jwenn yo itilize l anpil, genyen l nan majorite makèt panyòl yo. Yo itilize l tradisyonèlman pou sipòte bon fonksyònman ren yo (kidneys) ak aparèy irinè. Se yon bon dyeretik, kidonk li fè w pipi byen ak pi fasil.</p>
<p><strong>Kèk Byenfè Medisinal Tradisyonèl:</strong></p>
<p>– Pwoblèm ren ak vesi (blad pise), yon bon dyeretik</p>
<p>– Enfeksyon irinè, kanal brile</p>
<p>– Bon pou po, cheve ak zong, paske l chaje silika ladan l</p>
<p>– Li bon pou zo tou</p>
<p>– Dyeretik</p>
<p>-Antienflamatwa</p>
<p>– Antiyoksidan</p>
<p>– Sikatrizan, ede geri blese ou maleng pi rapid</p>
<p>– Netwaye, dezefektan, li bon anpil nan netwaye, yo toujou konn itilize l pou foubi bagay, pou klin ak elimine grès ki kole sou yon bagay.<br><br></p>
<p><br><strong>Dòz Kont Pwoblèm Krache San</strong></p>
<p><em>Krache San:</em> Men youn nan puisans medisinal plant Ke Chwal genyen se nan ede fikse pwoblèm krache san an. Youn nan resèt granmoun yo konn sere se lè yo itilize plant sa pou kanpe san an nan krache kèk malad. Men s ayo fè: pran plant lan tou ankè a, sa vle di ak tout rasin, ou ka pran 1-2 swivan gwosè pye a, mete l bouyi pou 7-10 minit nan 1 lit dlo (anviwon 2 bidon regilye yo). Ou ak bwè 1 tas 2-3 fwa pa jou swivan bezwen; ou ka kanpe nan demen depi san an fin kanpe, lè w pa wè tras li ann krache a ankò.</p>
<p>Pou krache san an tou pa bliye youn nan remèd efikas anpil se sik plant ki rele planten an: pran 3 kiyè pandan 3 fwa nan jounen an, l ap ede kanpe san an nan krache w rapid. Si sa pa mache ale lopital rapid. W ap jwenn plis detay sou plant sa sou Medikaplant plis lòt dòz. Pa janm gen yon sèl remèd natirèl pou yon pwoblèm sante. Se sa ki fè richès remèd natirèl.<br><br><br></p>
<p><strong>Dyare</strong>:</p>
<p>Ou ka fè menm dòz dekoskyon sa ak menm dozaj ak pozoloji a, sa vle di fè l menm jan an pou kanpe dyare. Si w vle ou ka ranfòse l ak de twa fèy gwayav oswa po gwayav.</p>
<p><strong>Emoraji, San Koule:</strong></p>
<p>W ap aplike menm resèt sa tou si w gen emoraji, li mache byen tou.</p>
<p>Sante w se responsabilite w. Tout pòs nou yo la pou rezon enfòmasyonèl, konsa n ap klere antèn ou sou enpòtans plant yo ak byenfè medisinal yo. Men toujou pran responsabilite pa w pou fè rechèch ou epi konsilte pwofesyonèl sante w pou konnen si w ka konsome yon plant ou pa. Fanm ansent oswa k ap bay tete oubyen moun ki fenk opere oswa ki soufri yon malad kèlkonk, dwe evite bwè te plant sa. Pòs sa yo pa konsèy medikal ni dwe ranplase dyagnostik ak preskrisyon pwofesyonèl sante w ka ba ou.</p>
<p><strong>Medikaplant</strong></p>
<p>www.Medikaplant.org</p>
<p>Medsi Tradisyonèl Ayisyen</p>
<p>Anpil nan nou ki sou paj la chak jou, poko janm Follow (abòne) ak paj la. Si w renmen travay la ak pa vle rate anyen, Follow paj la kounye a.</p>
<p>🌿 Beny pou Pye Cho: Sipò pou sikilasyon, cho-frèt, kout pye, “batri”</p>
<p>Tretman pou Maladi Fredite nan Medsin Tradisyonèl</p>
<p>🌺 SORÈL | FLÈ IBISIK | FLè Jamayik</p>
<p>🌿 Klin-tòks | Clean-Tox | Key Detox Herbs</p>
<p>🌿✨ Folat: Seròm Biyo Ki Ka Ede Timoun Yo Devlope Pi Byen✨🌿</p>
<p>🌿 DÒZ POU KOUPE DYARE KI PA VLE KANPE SOU TIMOUN</p>
<p>🔍 Hizòp Vs, Bazilik: Diferans Kle</p>
<p>🌿 RASIN VETIVÈ: YON TREZÒ MEDISINAL NOU NEGLIJE</p>
<p>Detòks: Pwotokòl Antiparazit &amp; Lyennaj (Binder)</p>
<p>Kèk bagay ou dwe fè anvan ou kòmanse nenpòt gerizon natirèl</p>', (select id from public.doz_categories where slug = 'doz-ak-fomil'), true, now()),
  ('damiana', 'Damiana: Plant Afwodizyak', 'Afwodizyak', 'Non syantifik: Turnera diffusa | aphrodisiaca (lòt espès ou ka sèvi) Non Famasetik: Folium Turnerae Anglè: Damiana, Mexican damiana, Mexican holly, Panyòl: Pastorcita, Hierba de…', '<p><strong>Non syantifik: Turnera diffusa | aphrodisiaca (lòt espès ou ka sèvi)<br>Non Famasetik: Folium Turnerae<br>Anglè: Damiana, Mexican damiana, Mexican holly,<br>Panyòl: Pastorcita, Hierba de la pastora, Hierba del venao, Damiane, Misibcoc.<br>Franse: Thym savane</strong><br><br></p>
<p><strong><em>Gou Plant lan: Anmè, rak<br>Se yon plant cho, sèk, elatriye</em></strong></p>
<p>Youn nan gwo plant ki efikas pou trete pwoblèm andirans, bann, fanm kou gason ki manke apeti taye, moun ki manke sou sa, moun libido yo ba, gason kòlmòzò mòlòlò bonjou pwèl, feblès seksyèl, nèg k ap tonbe sou teren pandan match la, nèg 1 grenn ke se bout yo k pa bay tout kalite eskiz. <br><br>Men jan w ka prepare ak doze plant sa si w ta vle eseye li: bouyi 1 ti kiyè pou chak gode dlo, pou yon 5-7 minit ou ka ajoute ti siwomyèl. Pozoloji: Limite tèt nou ak 2-3 tas pa jou. Si se nan boutèy tranpe nan kleren 1-4 ti chòt X jou. Pinga malè abize kosomasyon plant sa twòp. Limite kante w ap pran chak jou.</p>
<blockquote>
<p>Anpil moun ki nan domèn remèd natirèl konnen Damiana men yo pa konnen lòt non li genyen, epi pa panse nou genyen l ann Ayiti. Wi nou genyen l e se li nou rele «&nbsp;<strong><em>ten savann</em></strong>&nbsp;» nan. Se yon plant awomatik ki nan lafanmi plant «&nbsp;mant&nbsp;» yo. Moun ki pa konnen panse se yon raje li ye ann Ayiti poutan se yon medikaman ki vann anpil nan plizyè peyi sou latè. Se menm li menm tou yo bay non <strong>Orèg Mawon</strong> oswa <strong>Zonbi Nan Bwa</strong> nan kèk lòt lokalite.</p>
</blockquote>
<p>Se youn nan gwo afwodizyak ki genyen sou latè men an Ayiti nou genyen l, nou plis itilize l pou <strong>balonnman, gaz, gonfleman </strong>ak<strong> dijesyon</strong>. Se fèy la nou konn bouyi. Tandiske gason mòlòlò k ap fè bèk atè yo ta dwe itilize plant sa. Se pa lyann bande, bwa kochon, zo devan, elatriye pou n ap pede itilize sèlman. Gen yon pil lòt plant ki nan peyi a, yo pran pou raje men se plant ki puisan anpil. Se youn nan plant pou bann ak bande ki popilè sou mache entènasyonal la. </p>
<p><strong>Kèk Lòt Fason w Ka Itilize Plant sa Pou Ogmante Libido, Bann, Stamina</strong><br>Ou ka chode fèy la ak flè a nan dlo cho (enfizyon) pou yon ti tan, epi apre ou pase l nan paswa ou bwè, oswa ou ka tranpe l nan yon ti kleren lese l byen tranpe epi w ka pran yon ti bagay ladan l anvan w ale fè bagay (relasyon seksyèl). Si w gen yon boutèy bann oswa yon ti kleren (Ronm, Gin, Vodka, ets) ou ka mete kèk ti branch fèy ak flè tranpe pou omwen 10 jou, ou ka itilize gwòg melanj sa lè w vle pou revitalize enèji w, mete gason sou ou, paske yon konba ret yon konba.</p>
<p>Ten savann trete anpil maladi tankou enfeksyon irinè, li balanse òmon moun, si w gen anpil strès, perèz ak depresyon, si w toujou ap nève, plant sa ap ede fòtifye sistèm nève santral la epi kalme strès emosyonèl ou. Fèy la bon pou anpil koze tankou bwonchit, dyare, lafyèv, opresyon, se yon bon tonik pou nèf ak misk moun. Ou ka respire vapè plant lan bouyi pou kwape tèt fè mal, l ap fè w pipi. Plant sa chaje lòt benefis nou p ap ka fin site tankou li testostewogenik, antisepik, ekspektoran, laksatif (pa twò fò), ipo-tiwoyid, elariye. Chache definisyon tèm teknik yo sou paj a.</p>
<p><strong><em>ATANSYON</em></strong>: M pa ankouraje moun fimen menm, men gen oun ki fimen plant sa pou yo ka hay. Li gen puisans pou voye moun nan nyaj vre, yo ka itlize l pou fè w reve ou vwayaje ant somèy revèy, ou fè kèk eksperyans astral. Se pa yon plant pou n konsome anpil, asire n kontwole dozaj la oswa konsilte yon pwofesyonèl sante. Si w fè maladi sik, tansyon, si w pral opere nan espas 1-2 semèn, si w ansent oswa ap bay bebe tete pa konsome plant sa. Anpil fwa maladi sik fè n pèdi bann nou, plant sa pa bon solisyon an, gen lòt bagay nou ka pran tankou maka (Maca).</p>
<p><strong>Medikaplant</strong></p>
<p>➡️. Abòne | Like | Pataje pòs #Medikaplant pou n ka jwenn plis ak ede lòt moun jwenn èd gras ak plant nan lanati.</p>
<p>Sante w se responsabilite w<br>Toujou fè rechèch pèsonèl pa w<br>anvan w konsideran konsome plant, konsilte doktè w oswa pwofesyonèl swen sante w.</p>
<p>🌿 Beny pou Pye Cho: Sipò pou sikilasyon, cho-frèt, kout pye, “batri”</p>
<p>Tretman pou Maladi Fredite nan Medsin Tradisyonèl</p>
<p>🌺 SORÈL | FLÈ IBISIK | FLè Jamayik</p>
<p>🌿 Klin-tòks | Clean-Tox | Key Detox Herbs</p>
<p>🌿✨ Folat: Seròm Biyo Ki Ka Ede Timoun Yo Devlope Pi Byen✨🌿</p>
<p>🌿 DÒZ POU KOUPE DYARE KI PA VLE KANPE SOU TIMOUN</p>
<p>🔍 Hizòp Vs, Bazilik: Diferans Kle</p>
<p>🌿 RASIN VETIVÈ: YON TREZÒ MEDISINAL NOU NEGLIJE</p>
<p>Detòks: Pwotokòl Antiparazit &amp; Lyennaj (Binder)</p>
<p>Kèk bagay ou dwe fè anvan ou kòmanse nenpòt gerizon natirèl</p>', (select id from public.doz_categories where slug = 'doz-ak-fomil'), true, now()),
  ('fenigrek-fenugreek', 'Fenigrèk (Fenugreek): Yon Plant Nou Dwe Konnen', 'Nitrisyon', 'Non Syantifik: Trigonella foenum-graecum Fransè: Fenugrec | Trigonelle Fenugrec Anglè: Fenugreek Panyòl: Fenogreco Lòt non: Methi (Hindi) Se plis grenn Fenigrèk la yo itilize, se…', '<p><strong><em>Non Syantifik: Trigonella foenum-graecum<br>Fransè: Fenugrec | Trigonelle Fenugrec<br>Anglè: Fenugreek<br>Panyòl: Fenogreco<br>Lòt non: Methi (Hindi)</em></strong></p>
<p>Se plis grenn Fenigrèk la yo itilize, se yon legim grenn lan ye. Nou ka tou jwenn li an poud oswa nou ka achte grenn lan ankè epi nou pile yo; men tou nou ka itilize grenn lan pou fè te. Yo vann poud la sou fòm kapsil (li mache rapid). Nou ka itilize lwil esansyèl la tou sitou nan pwodui kosmetik yo.</p>
<p><strong>KÈK NAN POUVWA PLANT SA GENYEN:</strong></p>
<p>➡️ Fenigrèk la elimine mikoz (mucus) nan poumon, li mete yo djanm.<br>➡️ <strong>Enflamasyon</strong>: Li redui enflamasyon nan kò moun.<br>➡️ <strong>Lafyèv</strong>: Li elimine gòj fè mal epi li ka desann lafyèv trapde.<br>➡️ <strong>Dijesyon</strong>: Li rezoud pwoblèm apeti ou manje, ak ede konbat yon bann pwoblèm dijestif ou ka genyen.<br>➡️ <strong>Dyabèt</strong>: Li desann to sik nan san moun dyabetik yo. Li ede kontwole maladi sik. Sitou moun ki fè Dyabèt tip2 yo ka pran poud grenn fenigrèk la anviwon 2 fwa pa jou ant 5-100g. Ou ka pile grenn lan ou pran l nan dlo cho oswa ou bouyi grenn lan ou lese repoze, ou pase omwen 2-3 fwa nan paswa pou pare te a.<br>➡️ <strong>Kolestewòl</strong> ak <strong>Pèdi Pwa</strong> (Fonn Grès): Li gen lesitin (lecithin) ladan li ki ede elimine grès ak kolestewòl. Li diminiye vye kolestewòl epi ogmante bon kolestewòl.<br>➡️ Li ede jere yon nivo <strong>testostewòn</strong> nòmal.<br>➡️ <strong>Cheve</strong>: Lwil esansyèl la sitou bon pou moun ki gen pwoblèm cheve k ap tonbe, sa k pa founi, ki two fen, cheve sèk, tèt chòv ak kèk maladi nan po tèt. Ou ka itilize l nan melanj w ap fè pou fè tretan cheve ou nan pwodui pou pran swen cheve nou. <br></p>
<p><strong>MANMAN KI GEN PWOBLÈM LÈT<br></strong>➡️ Laktasyon | Pwoblèm Lèt: Li ede fanm ki pa gen ase lèt.<br>Pou Lèt la nou ka fè te a konsa pou kont li oswa nou melanje Fenigrèk la ansanm ak lòt plant tankou safran ak jenjanm. Ou ka melanje Fenigrèk ansanm ak Lanni + Gwo Ten (dous) + Chadwon Mari (Milk Thistle).</p>
<p><br>👉 Gen moun yo ki itilize sitou lwil esansyèl Fenigrèk la pou mase tete yo pou rann yo vin pi gwo epi djougan, pi doubout.<br></p>
<p><strong>PREPARASYON ESTANDA:<br></strong>1) Ou ka ajoute anviwon 1 kiyè grenn Fenigrèk nan vè dlo bouyi, brase l epi lese l chita pou anviwon 10-15 minit, apre sa ou ka bwè l konsa oswa pase l nan paswa si w pa ka sipòte ma a.<br>2) OU ka ajoute l nan je blennde w ap fè tou.<br></p>
<p>Malerezman, nou pa vrèman jwenn li ann Ayiti si se pa achte nou achte l nan men moun ou boutik ki enpòte l. #Medikaplant gen òganik la nan USA epi konn genyen l disponib Leyogàn-Ayiti tou. Li se plabt nbatif natal Ewòp ak Azi men si w nan Amerik Nò ou ka jwenn li byen fasil, ou ka achte l nan magazen ou sou nèt.<br><br></p>
<p>Avètisman: Nou espere w fè rechèch pèsonèl ou sou chak plant ou chwazi konsome menm si w jwenn li sou paj nou, yon fason pou w ka byen enfòme sou kont-endikasyon ak dozaj. Si w ap pran medikaman toujou konsilte doktè w ou pwofesyonèl sante w anvan w pran yon lòt remèd. Nou pa fè dyagnostik ni baw konsèy medikal. Nou pataje konesans plant anndan tradiyon medsin fèy.</p>
<p><br>Medikaplant</p>
<p>🌿 Beny pou Pye Cho: Sipò pou sikilasyon, cho-frèt, kout pye, “batri”</p>
<p>Tretman pou Maladi Fredite nan Medsin Tradisyonèl</p>
<p>🌺 SORÈL | FLÈ IBISIK | FLè Jamayik</p>
<p>🌿 Klin-tòks | Clean-Tox | Key Detox Herbs</p>
<p>🌿✨ Folat: Seròm Biyo Ki Ka Ede Timoun Yo Devlope Pi Byen✨🌿</p>
<p>🌿 DÒZ POU KOUPE DYARE KI PA VLE KANPE SOU TIMOUN</p>
<p>🔍 Hizòp Vs, Bazilik: Diferans Kle</p>
<p>🌿 RASIN VETIVÈ: YON TREZÒ MEDISINAL NOU NEGLIJE</p>
<p>Detòks: Pwotokòl Antiparazit &amp; Lyennaj (Binder)</p>
<p>Kèk bagay ou dwe fè anvan ou kòmanse nenpòt gerizon natirèl</p>', (select id from public.doz_categories where slug = 'doz-ak-fomil'), true, now()),
  ('9-doz-natirel-detoks', '9 Dòz Natirèl pou Detòks ak Pwoblèm Gastro-Entestinal', 'Detòks', '1) Konstipasyon MASKRETI VYOLÈT | KARAPAT (Non syantifik: Ricinus Communis) Itilize lwil Risin nan (vèsyon famasi a), pa itilize lwil maskreti kreyòl nou fè ak grenn yo, sila nou…', '<p><strong>1) Konstipasyon</strong>&nbsp;<br>MASKRETI VYOLÈT | KARAPAT (Non syantifik: Ricinus Communis)<br>Itilize lwil Risin nan (vèsyon famasi a), pa itilize lwil maskreti kreyòl nou fè ak grenn yo, sila nou penyen cheve a ki plis konsantre a. Bwè kiyè lwil la yon sèl fwa pandan w ap pran dejene. Granmoun: 2-3 kiyè (15-45 mL anviwon) epi timoun 1/2-2 ti kiyè ki anvwon 5-15 mL. Lè w konstipe li enpòtan pou manje fwi ak legim. Ou bezwen bon fib, li enpòtan si w blennde ji pou w kite ma yo. Bwè dlo tyèd nan maten ak dlo frèch pandan tout jounen.</p>
<p><strong>2) Vant Fè Mal | Lachman | Kolik</strong>&nbsp;<br>KAMOMIY ou FLÈ SOLÈY (Non Syantifik: Matricaria recutita)<br>Bouyi 1 ponyen fèy nan 1 Lit dlo pou 10 minit. Pase nan paswa epi te a pare. Sikre l ak siwomyèl oswa rapadou ou sik wouj òganik.</p>
<p><strong>3) Endijesyon | Vomisman | Balonnman | Gaz</strong>&nbsp;<br>TIBONM | Mant (Mentha nemorosa)<br>Ou ka itilize Tibonm Mawon an tou, yo konn rele l Vilnerè nan kèk zòn (Salvia occidentalis)<br>Bouyi 1 ponyen fèy nan 1 Lit dlo pou 10 minit. Pase nan paswa epi te a pare. Li preferab pou w pran l ak 2-3 grenn sèl.<br>si w gen pwoblèm irinè nou dekonseye w bwè te sa.</p>
<p><strong>4) MOVE DIJESYON | GAZ | BALONNMAN</strong>&nbsp;<br>Engredyan: Fèy Papay | Lanni | Jenjanm | Tibonm | Gwo Ten</p>
<p><em>OU BEZWEN:&nbsp;</em>1-2 Fèy Papay + 3 branch Lanni + 3 bout Jenjanm + 1 ti ponyen Tibonm + 3-7 fèy Gwo Ten<br><br><strong>PREPARASYON:</strong><br>Graje/pile oswa blennde Jenjanm nan, ajoute nan 1+ lit dlo, kou l pral koumanse bouyi, ajoute tout fèy yo ansanm. Lese melanj lan bouyi pou 5-7 minit. Pase melanj lan nan paswa, vide nan tas pou bwè tyèd. Ajoute de twa gout sitwon oswa 3 grenn sèl. Pou gou ou ka pran l ak siwomyèl men sèl la se meyè opsyon pou gaz. 2-3 tas pa pou 7 jou. Si pwoblèm dijesyon an pèsiste ale wè yon pwofesyonèl sante ou ekri nou.<br></p>
<p><strong>5) TE MELANJ 3 PLANT pou Gaz | Gonfleman | Balonnman</strong>&nbsp;<br>ENGREDAN: TIBONM + WOMAREN + LAY<br>PREPARASYON: Netwaye yo tout ansanm epi melanje yo. Bouyi yo pandan 5 a 7 minit. Pase nan paswa ou grèp. Epi ajoute 2-3 grenn sèl.<br>Si w pa jwenn Womaren ou ka ranplase l ak yon ti jenjanm.</p>
<p><strong>6) LACHMAN | VOMISMAN | GAZ | VANT FÈ MAL | LAFYÈV</strong>&nbsp;<br>JENJANM (Zingiber officinale):<br>Lave yon mòso jenjanm frèch. Grajel ak tout po a, epi mete yon kiyè jenjanm graje sa (anviwon 5g) bouyi nan 1-2 tas dlo pandan 10-12 minit. Pase l nan paswa oswa nan yon grèp te. Bwè 2-3 fwa X jou pandan 3 jou. Si w gentan djanm ou pa oblije kontinye bwè l.<br>&nbsp;Li pa bon pou fanm ansent | manamn k ap bay timoun tete oswa tyovi ki gen pi piti pase 5 lane.</p>
<p><strong>7) LACHMAN | DYARE</strong>&nbsp;<br>GWAYAV (Psidium guayava):<br>Pran 7 fèy grayav frèch epi byen lave yo epi mete yo nan yon kaswòl ki gen 1-2 tas dlo. Ajoute yon ti priz sèl + yon ti priz sik<br>epi byen kouvri kaswòl la; bouyi l pou anviwon 12 minit. Koule te a epi l pare pou bwè. Bwè l kou tizann oswa pran 4-5 fwa X jou pandan 3 jou. Si lachman an kanpe anvan sa, sispann pran dòz la. Ale konsilte doktè.</p>
<p><strong>8) VANT FÈ MAL | ILSÈ</strong>&nbsp;<br>VETIVÈ (Vetiveria zizanioides)<br>Pran 3 branch fèy; si fèy yo sèch ou ka deside pile yo si w vle men lè sa w ap jis itilize yon kiyè poud fèy sila; si w itilize 3 branch frèch, w ap mete 3 branch vetivè yo nan yon veso ki gen 2-3 tas dlo ladan l. Bouyi melanj lan pandan 12 minit.<br>Pase l nan paswa oswa nan yon grèp te. Bwè 2-3 fwa X jou pandan 3 jou.<br>&nbsp;Li pa bon pou fanm ansent | manamn k ap bay timoun tete oswa tyovi ki gen pi piti pase 5 lane.</p>
<p><strong>9) GAZ | BALONNMAN</strong>&nbsp;<br>Jiwòf (Syzygium aromaticum)<br>Nan yon vè dlo ou mete 12 klou jiwòf ladan depi nan aswè nan demen maten bwè li kou w fin bwose dan w.</p>
<p><strong><em>Avètisman:</em></strong></p>
<p>&nbsp;Majorite dòz plant sa yo pa bon pou fanm ansent | manamn k ap bay timoun tete oswa tyovi ki gen pi piti pase 5 lane. Si se yon aplikasyon topikal (sou po), si se p ayon te w ap bwè ki pral anndedan kò a, li pa poze pwoblèm pou kategori moun nou site anlè yo la. Men nou dekouraje yo bwè te fèy pandan moman gwosès, lè w ap bay tete oswa timoun ki gen -5 ane.&nbsp;#Medikaplant&nbsp;rete kwè n ap fè pwòp rechèch pèsonèl pa nou sou chak grenn plant anvan nou konsome yo. Epi li enpòtan pou n konsilte pwofesyonèl sante ou doktè nou anvan e sitou si n nan lòt medikplant famasi.</p>
<p>&nbsp;PATAJE POU EDIKE PLIS MOUN | LIKE &amp; FOLLOW.<br><br><strong>Medikaplant</strong></p>
<p>🌿 Beny pou Pye Cho: Sipò pou sikilasyon, cho-frèt, kout pye, “batri”</p>
<p>Tretman pou Maladi Fredite nan Medsin Tradisyonèl</p>
<p>🌺 SORÈL | FLÈ IBISIK | FLè Jamayik</p>
<p>🌿 Klin-tòks | Clean-Tox | Key Detox Herbs</p>
<p>🌿✨ Folat: Seròm Biyo Ki Ka Ede Timoun Yo Devlope Pi Byen✨🌿</p>
<p>🌿 DÒZ POU KOUPE DYARE KI PA VLE KANPE SOU TIMOUN</p>
<p>🔍 Hizòp Vs, Bazilik: Diferans Kle</p>
<p>🌿 RASIN VETIVÈ: YON TREZÒ MEDISINAL NOU NEGLIJE</p>
<p>Detòks: Pwotokòl Antiparazit &amp; Lyennaj (Binder)</p>
<p>Kèk bagay ou dwe fè anvan ou kòmanse nenpòt gerizon natirèl</p>', (select id from public.doz_categories where slug = 'doz-ak-fomil'), true, now())
on conflict (slug) do update set
  title = excluded.title, tag = excluded.tag, excerpt = excluded.excerpt,
  body_html = excluded.body_html, category_id = excluded.category_id,
  published = excluded.published, published_at = excluded.published_at,
  updated_at = now();
