/**
 * Vendors the site's web fonts into app/fonts so `next build` never downloads
 * from Google Fonts (next/font/google fails the production build whenever
 * Google answers with a font URL that has no file extension).
 *
 * Each family is requested with the same CSS2 URL and User-Agent that
 * next/font/google used (via Next's own helpers), so the files are the exact
 * unhinted woff2s the old build self-hosted — every subset, not just latin.
 * Writes:
 *   - app/fonts/<family>-<subset>-<wght|weight>-<style>.woff2
 *   - app/fonts/<scope>-fonts.css: each family's size-adjusted fallback face
 *     (the metrics next/font/google generated) and its non-latin subset faces
 *     (unicode-range, so a browser only fetches them when a page needs those
 *     characters).
 * The latin files are declared with next/font/local in the layouts, which
 * preloads them.
 *
 *   node scripts/vendor-fonts.mjs
 *
 * Re-run after changing a family, weight or style below, and mirror the change
 * in the localFont() call that uses it.
 */
import fs from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const google = (name) => require(`next/dist/compiled/@next/font/dist/google/${name}`);
const { validateGoogleFontFunctionCall } = google('validate-google-font-function-call');
const { getFontAxes } = google('get-font-axes');
const { getGoogleFontsUrl } = google('get-google-fonts-url');
const { fetchResource } = google('fetch-resource');
const { calculateSizeAdjustValues } = require('next/dist/server/font-utils');

// Scopes: site = app/layout.tsx, laboratwa = app/laboratwa/layout.tsx,
// glose = app/glose/poppins.ts.
const FONTS = [
  { scope: 'site', fn: 'Playfair_Display', slug: 'playfair-display', weight: ['400', '500', '600', '700', '800'] },
  { scope: 'site', fn: 'Lora', slug: 'lora', weight: ['400', '500', '600'] },
  { scope: 'site', fn: 'DM_Sans', slug: 'dm-sans', weight: ['400', '500', '600', '700'] },
  { scope: 'laboratwa', fn: 'Petrona', slug: 'petrona', weight: ['400', '600'], style: ['normal', 'italic'] },
  { scope: 'laboratwa', fn: 'Archivo', slug: 'archivo', weight: ['400', '500', '600'] },
  { scope: 'laboratwa', fn: 'IBM_Plex_Mono', slug: 'ibm-plex-mono', weight: ['500'] },
  { scope: 'glose', fn: 'Poppins', slug: 'poppins', weight: ['400', '500', '600', '700'], style: ['normal', 'italic'] },
];
const OUT = 'app/fonts';

const sheets = {};
for (const font of FONTS) {
  const { fontFamily, weights, styles, selectedVariableAxes, display } = validateGoogleFontFunctionCall(font.fn, {
    weight: font.weight,
    style: font.style,
    subsets: ['latin'],
  });
  const url = getGoogleFontsUrl(fontFamily, getFontAxes(fontFamily, weights, styles, selectedVariableAxes), display);
  const css = (await fetchResource(url, false)).toString('utf8');

  // Google points every weight of a variable family at the same file, so
  // group its @font-face blocks by file.
  const files = new Map();
  for (const block of css.split('/* ').slice(1)) {
    const src = /src: url\((.+?)\)/.exec(block)[1];
    const file = files.get(src) ?? {
      subset: block.slice(0, block.indexOf(' */')),
      style: /font-style: (\w+)/.exec(block)[1],
      range: /unicode-range: ([^;]+);/.exec(block)[1],
      weights: [],
    };
    file.weights.push(Number(/font-weight: (\d+)/.exec(block)[1]));
    files.set(src, file);
  }

  const faces = [];
  for (const [src, file] of files) {
    const min = Math.min(...file.weights);
    const max = Math.max(...file.weights);
    const name = `${font.slug}-${file.subset}-${file.weights.length > 1 ? 'wght' : min}-${file.style}.woff2`;
    fs.writeFileSync(`${OUT}/${name}`, await fetchResource(src, false));
    if (file.subset === 'latin') continue;
    faces.push(`@font-face {
  font-family: '${fontFamily}';
  font-style: ${file.style};
  font-weight: ${min === max ? min : `${min} ${max}`};
  font-display: swap;
  src: url('./${name}') format('woff2');
  unicode-range: ${file.range};
}`);
  }

  const m = calculateSizeAdjustValues(fontFamily);
  const fallback = `@font-face {
  font-family: '${fontFamily} Fallback';
  src: local("${m.fallbackFont}");
  ascent-override: ${m.ascent}%;
  descent-override: ${m.descent}%;
  line-gap-override: ${m.lineGap}%;
  size-adjust: ${m.sizeAdjust}%;
}`;
  (sheets[font.scope] ??= []).push(`/* ${fontFamily} */\n${fallback}`, ...faces);
  console.log(`${fontFamily}: ${files.size} files`);
}

for (const [scope, blocks] of Object.entries(sheets)) {
  fs.writeFileSync(
    `${OUT}/${scope}-fonts.css`,
    `/* Generated by scripts/vendor-fonts.mjs — do not edit by hand. */\n\n${blocks.join('\n\n')}\n`
  );
}
