-- Admin-managed homepage graphics.
--
-- One row per overridden image slot. Slots themselves are declared in code
-- (lib/site-image-slots.ts, generated by scripts/gen-site-image-slots.mjs);
-- a missing row simply means "use the default shipped in the component", so
-- the homepage can never render a broken image and an admin can revert any
-- slot by deleting its row.
--
-- Applied to production before being exported here; written idempotently so
-- re-running against an existing database is a no-op.

create table if not exists public.site_images (
  key         text primary key,
  url         text        not null,
  alt         text,
  updated_at  timestamptz not null default now(),
  updated_by  uuid        references auth.users(id) on delete set null
);

alter table public.site_images enable row level security;

-- Anyone (including logged-out visitors) may read: these are public graphics.
drop policy if exists site_images_public_read on public.site_images;
create policy site_images_public_read
  on public.site_images
  for select
  using (true);

-- Only admins may add, change, or remove an override.
drop policy if exists site_images_admin_all on public.site_images;
create policy site_images_admin_all
  on public.site_images
  for all
  using (is_admin(auth.uid()))
  with check (is_admin(auth.uid()));
